#pragma once

#ifdef POINTING_DEVICE_ENABLE
#    define POINTING_DEVICE_SCLK_PIN C4
#    define POINTING_DEVICE_SDIO_PIN C5
#    define POINTING_DEVICE_MOTION_PIN C6
#    define POINTING_DEVICE_CS_PIN C7
#    define POINTING_DEVICE_INVERT_Y
//#    define POINTING_DEVICE_DEBUG
#endif

//#define NO_ACTION_TAPPING
//#define NO_ACTION_ONESHOT
